# Generated by Django 5.0 on 2023-12-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.RenameField(
            model_name='news',
            old_name='body',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.AddField(
            model_name='news',
            name='main_image',
            field=models.ImageField(default='default_image.jpg', upload_to='news_images/'),
        ),
        migrations.AddField(
            model_name='news',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/previews/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
