# Generated by Django 5.0 on 2023-12-07 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_alter_news_author_rename_body_news_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
