# Generated by Django 5.0 on 2023-12-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_news_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='preview_image',
        ),
    ]
