# Generated by Django 5.0 on 2023-12-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_remove_news_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_images/previews/'),
        ),
    ]
