# Generated by Django 5.0 on 2023-12-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0006_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
    ]
