# Generated by Django 5.0 on 2023-12-10 12:14

import django_admin_geomap
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0008_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, django_admin_geomap.GeoItem),
        ),
    ]
