# Generated by Django 5.0 on 2023-12-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0009_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
